services:
  postgres:
    image: 'postgres:latest'
    contrainer_name: 'auth-db'
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=auth
      - POSTGRES_DB=auth