application-version: 0.0.1-SNAPSHOT
application-description: Auth rest api

server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://172.17.0.1:5434/auth
    username: auth
    password: auth
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true

application:
  security:
    jwt:
      cookieName: jwt
      refreshCookieName: jwt-refresh
      secret: YiJW5JhK3uv6q8InoJgQYP3hmOEP/79009Y/6/Xeamxq9DnYSVZzU1m5iFRCNWymmBAmLmYmY2C1KcSqX5aELlN7fkLdJtehwaSjWotfrESvUIap6VI9GyMglmeuBPTfFQMHJM7qhLwZQXHIrA3sRjvSrDHNTffuEHmKqtWuXgIX%
      expirationMs: 3600000
      refreshExpirationMs: 86400000